/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'buyerEmail' : string,
  'storeId' : bigint,
  'createdAt' : Time,
  'buyerPrincipal' : [] | [Principal],
  'items' : Array<OrderItem>,
  'buyerName' : string,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'fulfilled' : null };
export interface Product {
  'id' : bigint,
  'storeId' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'category' : string,
  'imageId' : [] | [Uint8Array],
  'price' : bigint,
}
export interface Store {
  'id' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'slug' : string,
  'description' : string,
  'isActive' : boolean,
  'bannerImageId' : [] | [Uint8Array],
}
export interface StoreAnalytics {
  'totalOrders' : bigint,
  'topProducts' : Array<[bigint, string, bigint]>,
  'totalRevenue' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [bigint, string, string, bigint, bigint, string],
    bigint
  >,
  'aiAssist' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStore' : ActorMethod<[string, string, string], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteStore' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyStore' : ActorMethod<[], Store>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getStore' : ActorMethod<[bigint], Store>,
  'getStoreAnalytics' : ActorMethod<[bigint], StoreAnalytics>,
  'getStoreBySlug' : ActorMethod<[string], Store>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveProductsByStore' : ActorMethod<[bigint], Array<Product>>,
  'listAllStores' : ActorMethod<[], Array<Store>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listOrdersByStore' : ActorMethod<[bigint], Array<Order>>,
  'listProductsByStore' : ActorMethod<[bigint], Array<Product>>,
  'placeOrder' : ActorMethod<
    [bigint, string, string, Array<OrderItem>],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, bigint],
    undefined
  >,
  'updateStore' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];